server:
  port: 8080

spring:
  application:
    name: subscription
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/subees
    username: minsu
    password: 135246
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

logging:
  level:
    com.subees.subscription: debug

mybatis:
  type-aliases-package: com.subees.subscription.user.entity
  mapper-locations:
    - classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL

jwt:
  secret: subees1234subees1234subees1234subees1234
  access-token-expiration: 86400000

app:
  upload:
    dir: uploads/profile-images
  profile:
    default-image-url: https://example.com/images/default-profile.png
